import './globals.css'
import Script from 'next/script';

import './styles/flaticon.css';
import './styles/menu.css';
import './styles/dropdown-effects/fade-down.css';
import './styles/magnific-popup.css';
import './styles/owl.carousel.min.css';
import './styles/owl.theme.default.min.css';
import './styles/datetimepicker.min.css';
import './styles/lunar.css';
import './styles/animate.css';
import './styles/style.css';
import './styles/responsive.css';

import './styles/bootstrap.min.css'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export async function generateStaticParams() {
  return [{ lang: 'en-US' }, { lang: 'de' }]
}


export default function RootLayout({ children, params }) {

  const direction = params.lang === 'ar' ? 'rtl' : 'ltr';

  return (
    <html  lang={params.lang} dir={direction}>
      <body>
        {children}
        

  <Script src="/js/jquery-3.7.0.min.js" strategy="afterInteractive"/>
  <Script src="/js/bootstrap.min.js" strategy="afterInteractive" />
  <Script src="/js/modernizr.custom.js" strategy="afterInteractive" />
  <Script src="/js/jquery.easing.js" strategy="afterInteractive" />
  <Script src="/js/menu.js" strategy="afterInteractive" />
  <Script src="/js/materialize.js" strategy="afterInteractive" />
  <Script src="/js/tweenmax.min.js" strategy="afterInteractive" />
  <Script src="/js/slideshow.js" strategy="afterInteractive" />
  <Script src="/js/datetimepicker.js"  strategy="afterInteractive"/>
  <Script src="/js/owl.carousel.min.js" strategy="afterInteractive" />
  <Script src="/js/jquery.magnific-popup.min.js" strategy="afterInteractive" />
  <Script src="/js/request-form.js" strategy="afterInteractive" />
  <Script src="/js/jquery.validate.min.js" strategy="afterInteractive" />
  <Script src="/js/jquery.ajaxchimp.min.js" strategy="afterInteractive" />
  <Script src="/js/popper.min.js" strategy="afterInteractive" />
  <Script src="/js/lunar.js" strategy="afterInteractive" />
  <Script src="/js/wow.js" strategy="afterInteractive" />
  <Script src="/js/custom.js" strategy="afterInteractive" />
      </body>
    </html>
  )
}
